# Generated by Django 3.0.3 on 2020-03-05 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaoSat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Cau1', models.BooleanField(default=False)),
                ('Cau2', models.BooleanField(default=False)),
                ('Cau3', models.BooleanField(default=False)),
                ('Cau4', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('generation', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
