# Generated by Django 3.0.3 on 2020-03-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khaosat',
            name='Lydo_Cau2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='khaosat',
            name='Lydo_Cau3',
            field=models.CharField(default='', max_length=300),
        ),
    ]
